# Generated by Django 4.0.3 on 2022-04-06 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=3)),
                ('patient_name', models.CharField(max_length=70)),
                ('doctor_id', models.CharField(max_length=3)),
                ('doctor_name', models.CharField(max_length=70)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')])),
                ('lastname', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('-', 'Decline to Answer')], max_length=1)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('accepts_new_patients', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('-', 'Decline to Answer')], max_length=1)),
                ('weight', models.PositiveSmallIntegerField()),
                ('height_ft', models.PositiveSmallIntegerField()),
                ('height_in', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)])),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
            ],
        ),
    ]
