# Generated by Django 4.0.3 on 2022-03-31 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='firstname',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-dA-d]+$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Decline to Answer', 'Decline to Answer')], max_length=17),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastname',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-dA-d]+$')]),
        ),
    ]
