# Generated by Django 4.0.3 on 2022-04-06 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 6)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 6, 14, 4, 16, 564494)),
            preserve_default=False,
        ),
    ]
