# Generated by Django 4.0.3 on 2022-04-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment_date_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_exists',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_exists',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
