# Generated by Django 4.0.3 on 2022-03-31 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_firstname_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='firstname',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastname',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')]),
        ),
    ]
