# Generated by Django 4.0.3 on 2022-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_doctor_exists_appointment_patient_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='firstname',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(max_length=35),
        ),
    ]
