# Generated by Django 4.0.3 on 2022-03-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_firstname_alter_patient_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('-', 'Decline to Answer')], max_length=1),
        ),
    ]
