# Generated by Django 4.0.3 on 2022-03-31 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')])),
                ('lastname', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('-', 'Decline to Answer')], max_length=1)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('availability', models.JSONField()),
            ],
        ),
    ]
