# Generated by Django 4.0.3 on 2022-04-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_appointment_doctor_exists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='accepts_new_patients',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3),
        ),
    ]
