# Generated by Django 4.0.3 on 2022-04-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_doctor_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='firstname',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastname',
            field=models.CharField(max_length=35),
        ),
    ]
