# Generated by Django 4.0.3 on 2022-04-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_patient_firstname_alter_patient_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=4)),
                ('doctor', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('time', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
