# Generated by Django 4.0.3 on 2022-04-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_first',
            field=models.CharField(default='julie', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.CharField(default='1', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_last',
            field=models.CharField(default='chen', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_first',
            field=models.CharField(default='natalie', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.CharField(default='3', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_last',
            field=models.CharField(default='cho', max_length=35),
            preserve_default=False,
        ),
    ]
