# Generated by Django 4.0.3 on 2022-04-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_appointment_doctor_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_first',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_last',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_first',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_last',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default='natalie chen', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='julie chen', max_length=70),
            preserve_default=False,
        ),
    ]
