# Generated by Django 4.0.3 on 2022-04-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_appointment_doctor_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
